In [7]:
import numpy as np
import array

In [8]:
array.array('i', [1, 2, 3, 4])

array('i', [1, 2, 3, 4])

In [9]:
# creates np array from list
np.array([1, 2, 3, 4, 5, 6, 7, 8])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [10]:
# creates np array of 10 zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
# creates np array with dim. 3x5 filled with ones
np.ones((3, 5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [16]:
# creates np array with given dim. filled with |value|
np.full(3, 3.14, dtype="float32")

array([3.14, 3.14, 3.14], dtype=float32)

In [19]:
# create array with linear sequence from 0 to 20 steping by 4
np.arange(0, 20, 4)

array([ 0,  4,  8, 12, 16])

In [21]:
# creates array lineary spaced from 1 to 20 with 5 values
np.linspace(1, 20, 5, dtype="float32")

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ], dtype=float32)

In [22]:
# creates a random array of uniformy value from 0 to 1
np.random.random((3, 3))

array([[0.18915274, 0.5167096 , 0.17293167],
       [0.68881401, 0.74741487, 0.88323804],
       [0.2922808 , 0.96561577, 0.70440758]])

In [34]:
# creates an array with normaly distributed values with 10 mean and 1 std. dev.
np.random.normal(10, 1, (2,2))

array([[10.9489777 , 10.34172162],
       [ 9.31078181, 10.38356749]])

In [37]:
# creates an array with random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[1, 6, 2],
       [1, 9, 5],
       [5, 0, 1]])

In [41]:
# 3x3 identity matrix 
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [43]:
# creates an uninitialized array, the values will be whatever is in memory
np.empty(6)

array([4.64260319e-310, 0.00000000e+000, 4.64190442e-310, 4.64190447e-310,
       1.14587773e-312, 1.90979621e-312])

In [ ]:
# Numpy Atributes