In [2]:
import numpy as np

In [3]:
# Broadcasting
# rules: values has to have at least 1 equal dim. length or be 1 dim.

a = np.array([0, 1, 2])
b = np.array([5])
a + 2 # returns an array with each element of "a" + 2

array([2, 3, 4])

In [4]:
# rows
M = np.ones((2, 3))
a = np.arange(3)
a, a.shape, M, M.shape, a + M

(array([0, 1, 2]),
 (3,),
 array([[1., 1., 1.],
        [1., 1., 1.]]),
 (2, 3),
 array([[1., 2., 3.],
        [1., 2., 3.]]))

In [5]:
# cols
M = np.ones((3, 2))
a = a.reshape((3, 1))
a, a.shape, M, M.shape, a + M

(array([[0],
        [1],
        [2]]),
 (3, 1),
 array([[1., 1.],
        [1., 1.],
        [1., 1.]]),
 (3, 2),
 array([[1., 1.],
        [2., 2.],
        [3., 3.]]))

In [6]:
# error
a = np.arange(4) # [0, 1, 2, 3] shape: (4, )
M = np.ones((2, 2)) # [[1, 1], [1, 1]] shape: (2, 2)
try:
    a + M # Error
except ValueError as e:
    print(e)

operands could not be broadcast together with shapes (4,) (2,2) 


In [7]:
a = np.arange(3) # [0, 1, 2] shape: (3, )
M = np.ones((3, 2)) # [[1, 1, 1], [1, 1, 1] shape: (3, 2)
try:
    a + M # Error
except ValueError as e:
    print(e, a, M, sep='\n')

operands could not be broadcast together with shapes (3,) (3,2) 
[0 1 2]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [8]:
X = np.random.random((10, 3))
X_centered = X - X.mean(0)
X[:3], X_centered[:3], X_centered.mean()

(array([[0.21169983, 0.46192126, 0.72526775],
        [0.43198169, 0.81759659, 0.75035011],
        [0.30329713, 0.47155101, 0.40610147]]),
 array([[-0.16791348, -0.06357519,  0.11046442],
        [ 0.05236838,  0.29210014,  0.13554678],
        [-0.07631618, -0.05394544, -0.20870186]]),
 5.181040781584064e-17)

In [9]:
# ploting a 2D function
x = np.linspace(0, 5, 25) # [0..5]
#y_ = np.linspace(0, 5, 25)[np.newaxis] # [ [0..5], ]
y = np.linspace(0, 5, 25)[:, np.newaxis] # [ [0], [0.2], [0.4], ... [5]] .reshape((25, 1))

z = np.sin(x) ** 10 + np.cos(10 + x + y) * np.cos(x)
z

array([[-0.83907153, -0.69309056, -0.50018294, -0.28898896, -0.05925713,
         0.25305805,  0.67173158,  0.98869277,  0.89549205,  0.3942392 ,
        -0.18153427, -0.57804587, -0.79348532, -0.8983018 , -0.91561119,
        -0.84786564, -0.70682654, -0.51654778, -0.30609505, -0.07943435,
         0.22347257,  0.63772214,  0.9754172 ,  0.92082118,  0.44192559],
       [-0.70840863, -0.53527957, -0.33104839, -0.126293  ,  0.08033982,
         0.35684814,  0.73313399,  1.00837982,  0.88127414,  0.35972832,
        -0.21925372, -0.60134044, -0.78718988, -0.85231446, -0.82662191,
        -0.7199226 , -0.55064345, -0.34767062, -0.14224193,  0.06253632,
         0.33044674,  0.70257418,  0.99822913,  0.90886868,  0.40843303],
       [-0.54710988, -0.35431986, -0.14759222,  0.04206797,  0.21859691,
         0.45514388,  0.78844884,  1.02504887,  0.87024531,  0.33668902,
        -0.23656091, -0.59615381, -0.74659669, -0.76946055, -0.70188451,
        -0.56084577, -0.37064722, -0.16375462,  0

In [10]:
%matplotlib inline
import matplotlib.pyplot as plt

In [11]:
#plt.imshow(z, origin="lower", extent=[0, 5, 0, 5], cmap="viridis")
#plt.colorbar()